/*
 * SEPP Telescopic FQDN Mapping API
 *
 * SEPP Telescopic FQDN Mapping Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * Source file: 3GPP TS 29.573 V16.3.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InvalidParam struct {
	Param string `json:"param" yaml:"param" bson:"param"`
	Reason string `json:"reason,omitempty" yaml:"reason" bson:"reason"`
}
