/*
 * JOSE Protected Message Forwarding API
 *
 * N32-f Message Forwarding Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package JOSEProtectedMessageForwarding

import (
	"encoding/json"
	"io/ioutil"
	"net/http"

	"github.com/free5gc/http_wrapper"
	"github.com/yangalan0903/openapi"
	"github.com/yangalan0903/openapi/models"
	"github.com/yangalan0903/sepp/logger"
	"github.com/yangalan0903/sepp/producer"
)

// N32fProcessOptions - Discover communication options supported by next hop (IPX or SEPP)
func N32fProcessOptions(rspWriter http.ResponseWriter, request *http.Request) {
	rspWriter.Write(nil) // ctx.JSON(http.StatusOK, gin.H{})
}

// PostN32fProcess - N32-f Message Forwarding
func PostN32fProcess(rspWriter http.ResponseWriter, request *http.Request) {
	var n32fReformattedReqMsg models.N32fReformattedReqMsg

	requestBody, err := ioutil.ReadAll(request.Body)
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.N32fForward.Errorf("Get Request Body error: %+v", err)
		rspWriter.WriteHeader(http.StatusInternalServerError)
		rsp, err := json.Marshal(problemDetail)
		if err != nil {
			logger.Handshake.Errorf("Encode problemDetail error: %+v", err)
		}
		rspWriter.Write(rsp)
		// ctx.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&n32fReformattedReqMsg, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rspBody := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.Handshake.Errorln(problemDetail)
		rspWriter.WriteHeader(http.StatusBadRequest)
		rsp, err := json.Marshal(rspBody)
		if err != nil {
			logger.Handshake.Errorf("Encode problemDetail error: %+v", err)
		}
		rspWriter.Write(rsp)
		// ctx.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := http_wrapper.NewRequest(request, n32fReformattedReqMsg)

	rsp := producer.HandleN32forwardMessage(req)

	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
	if err != nil {
		logger.Handshake.Errorln(err)
		problemDetails := models.ProblemDetails{
			Status: http.StatusInternalServerError,
			Cause:  "SYSTEM_FAILURE",
			Detail: err.Error(),
		}
		rspWriter.WriteHeader(http.StatusInternalServerError)
		rsp, err := json.Marshal(problemDetails)
		if err != nil {
			logger.Handshake.Errorf("Encode problemDetail error: %+v", err)
		}
		rspWriter.Write(rsp)
		// ctx.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		rspWriter.Header().Add("Content-Type", "application/json")
		rspWriter.Write(responseBody)
		// ctx.Data(rsp.Status, "application/json", responseBody)
	}
}
