/*
 * JOSE Protected Message Forwarding API
 *
 * N32-f Message Forwarding Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package JOSEProtectedMessageForwarding

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// N32fProcessOptions - Discover communication options supported by next hop (IPX or SEPP)
func N32fProcessOptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostN32fProcess - N32-f Message Forwarding
func PostN32fProcess(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
