/*
 * SEPP Telescopic FQDN Mapping API
 *
 * SEPP Telescopic FQDN Mapping Service. © 2019, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package TelescopicFqdnMapping

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetTelescopicMapping - Maps an FQDN to/from a telescopic FQDN
func GetTelescopicMapping(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
