info:
  version: 1.0.0
  description: SEPP test configuration

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false

localPLMNID: "20910"
seppID: "vSEPP"

listenAddr: "0.0.0.0"
listenPort: 29532

# tls: # the local path of TLS key
#   pem: cert/sepp.pem # SEPP TLS Certificate
#   key: cert/sepp.key # SEPP TLS Private key

configuration:
  fqdnSupportList:
    - fqdn: "tngf.free5gc.org"
      ipForSbi: "127.0.0.1"
      ipForN32f: "127.0.0.1"

  sbi:
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.1
    bindingIPv4: 0.0.0.0
    port: 29532 # port used to bind the service
    ipv4ForN32f: "127.0.0.1"

  nrfUri: http://127.0.0.10:8000
  nrfCertPem: cert/nrf.pem

  plmnSupportList:
    - mcc: "208"
      mnc: "93"


peerSEPP:
  plmnID: "20893"
  uri: "https://192.168.56.109:29532"
  seppID: "hSEPP"

  # tls: # the local path of TLS key
  #   pem: cert/pcf.pem # PCF TLS Certificate
  #   key: cert/pcf.key # PCF TLS Private key

logLevel: "info"
logFile: "logs/sepp.log"


