info:
  version: 1.0.0
  description: SEPP config for vPLMN (20893)

logger:
  enable: true
  level: debug
  reportCaller: false

configuration:
  fqdn: "vsepp.free5gc.org"

  sbi:
    scheme: http
    registerIPv4: 192.168.56.109
    bindingIPv4: 0.0.0.0
    port: 29533
    iPv4ForN32f: 192.168.56.109

  fqdnSupportList:
    - fqdn: "hsepp.free5gc.org"
      scheme: http
      port: 29533
      ipForSBI: "192.168.56.111"
      ipForN32f: "192.168.56.111"

  nrfUri: "http://192.168.56.109:8000"
  ipxUri: "http://192.168.56.109:29533"

  plmnSupportList:
    - mcc: "208"
      mnc: "93"
