/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved.
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handshake

import (
	"net/http"
)

// PostN32fError - N32-f Error Reporting Procedure
func PostN32fError(rspWriter http.ResponseWriter, request *http.Request) {
	rspWriter.Write(nil)
}
