/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type N32fErrorInfo struct {
	N32fMessageId string `json:"n32fMessageId" yaml:"n32fMessageId" bson:"n32fMessageId" mapstructure:"N32fMessageId"`
	N32fErrorType N32fErrorType `json:"n32fErrorType" yaml:"n32fErrorType" bson:"n32fErrorType" mapstructure:"N32fErrorType"`
	FailedModificationList []FailedModificationInfo `json:"failedModificationList,omitempty" yaml:"failedModificationList" bson:"failedModificationList" mapstructure:"FailedModificationList"`
	ErrorDetailsList []N32fErrorDetail `json:"errorDetailsList,omitempty" yaml:"errorDetailsList" bson:"errorDetailsList" mapstructure:"ErrorDetailsList"`
}
