/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type FailureReason string

// List of FailureReason
const (
	FailureReason_JSON_POINTER FailureReason = "INVALID_JSON_POINTER"
	FailureReason_INDEX_TO_ENCRYPTED_BLOCK FailureReason = "INVALID_INDEX_TO_ENCRYPTED_BLOCK"
	FailureReason_HTTP_HEADER FailureReason = "INVALID_HTTP_HEADER"
)