/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type IeLocation string

// List of IeLocation
const (
	IeLocation_URI_PARAM IeLocation = "URI_PARAM"
	IeLocation_HEADER IeLocation = "HEADER"
	IeLocation_BODY IeLocation = "BODY"
	IeLocation_MULTIPART_BINARY IeLocation = "MULTIPART_BINARY"
)