/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type IpxProviderSecInfo struct {
	// Fully Qualified Domain Name
	IpxProviderId string `json:"ipxProviderId" yaml:"ipxProviderId" bson:"ipxProviderId" mapstructure:"IpxProviderId"`
	RawPublicKeyList []string `json:"rawPublicKeyList,omitempty" yaml:"rawPublicKeyList" bson:"rawPublicKeyList" mapstructure:"RawPublicKeyList"`
	CertificateList []string `json:"certificateList,omitempty" yaml:"certificateList" bson:"certificateList" mapstructure:"CertificateList"`
}
