/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type HttpMethod string

// List of HttpMethod
const (
	HttpMethod_GET HttpMethod = "GET"
	HttpMethod_PUT HttpMethod = "PUT"
	HttpMethod_POST HttpMethod = "POST"
	HttpMethod_DELETE HttpMethod = "DELETE"
	HttpMethod_PATCH HttpMethod = "PATCH"
	HttpMethod_HEAD HttpMethod = "HEAD"
	HttpMethod_OPTIONS HttpMethod = "OPTIONS"
	HttpMethod_CONNECT HttpMethod = "CONNECT"
	HttpMethod_TRACE HttpMethod = "TRACE"
)