/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SecParamExchRspData struct {
	N32fContextId string `json:"n32fContextId" yaml:"n32fContextId" bson:"n32fContextId" mapstructure:"N32fContextId"`
	SelectedJweCipherSuite string `json:"selectedJweCipherSuite,omitempty" yaml:"selectedJweCipherSuite" bson:"selectedJweCipherSuite" mapstructure:"SelectedJweCipherSuite"`
	SelectedJwsCipherSuite string `json:"selectedJwsCipherSuite,omitempty" yaml:"selectedJwsCipherSuite" bson:"selectedJwsCipherSuite" mapstructure:"SelectedJwsCipherSuite"`
	SelProtectionPolicyInfo *ProtectionPolicy `json:"selProtectionPolicyInfo,omitempty" yaml:"selProtectionPolicyInfo" bson:"selProtectionPolicyInfo" mapstructure:"SelProtectionPolicyInfo"`
	IpxProviderSecInfoList []IpxProviderSecInfo `json:"ipxProviderSecInfoList,omitempty" yaml:"ipxProviderSecInfoList" bson:"ipxProviderSecInfoList" mapstructure:"IpxProviderSecInfoList"`
	// Fully Qualified Domain Name
	Sender string `json:"sender,omitempty" yaml:"sender" bson:"sender" mapstructure:"Sender"`
}
