/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type IeType string

// List of IeType
const (
	IeType_UEID IeType = "UEID"
	IeType_LOCATION IeType = "LOCATION"
	IeType_KEY_MATERIAL IeType = "KEY_MATERIAL"
	IeType_AUTHENTICATION_MATERIAL IeType = "AUTHENTICATION_MATERIAL"
	IeType_AUTHORIZATION_TOKEN IeType = "AUTHORIZATION_TOKEN"
	IeType_OTHER IeType = "OTHER"
	IeType_NONSENSITIVE IeType = "NONSENSITIVE"
)