/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type IeInfo struct {
	IeLoc IeLocation `json:"ieLoc" yaml:"ieLoc" bson:"ieLoc" mapstructure:"IeLoc"`
	IeType IeType `json:"ieType" yaml:"ieType" bson:"ieType" mapstructure:"IeType"`
	ReqIe string `json:"reqIe,omitempty" yaml:"reqIe" bson:"reqIe" mapstructure:"ReqIe"`
	RspIe string `json:"rspIe,omitempty" yaml:"rspIe" bson:"rspIe" mapstructure:"RspIe"`
	IsModifiable bool `json:"isModifiable,omitempty" yaml:"isModifiable" bson:"isModifiable" mapstructure:"IsModifiable"`
	IsModifiableByIpx map[string]bool `json:"isModifiableByIpx,omitempty" yaml:"isModifiableByIpx" bson:"isModifiableByIpx" mapstructure:"IsModifiableByIpx"`
}
