/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ApiIeMapping struct {
	ApiSignature *ApiSignature `json:"apiSignature" yaml:"apiSignature" bson:"apiSignature" mapstructure:"ApiSignature"`
	ApiMethod HttpMethod `json:"apiMethod" yaml:"apiMethod" bson:"apiMethod" mapstructure:"ApiMethod"`
	IeList []IeInfo `json:"IeList" yaml:"IeList" bson:"IeList" mapstructure:"IeList"`
}
