/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SecParamExchReqData struct {
	N32fContextId string `json:"n32fContextId" yaml:"n32fContextId" bson:"n32fContextId" mapstructure:"N32fContextId"`
	JweCipherSuiteList []string `json:"jweCipherSuiteList,omitempty" yaml:"jweCipherSuiteList" bson:"jweCipherSuiteList" mapstructure:"JweCipherSuiteList"`
	JwsCipherSuiteList []string `json:"jwsCipherSuiteList,omitempty" yaml:"jwsCipherSuiteList" bson:"jwsCipherSuiteList" mapstructure:"JwsCipherSuiteList"`
	ProtectionPolicyInfo *ProtectionPolicy `json:"protectionPolicyInfo,omitempty" yaml:"protectionPolicyInfo" bson:"protectionPolicyInfo" mapstructure:"ProtectionPolicyInfo"`
	IpxProviderSecInfoList []IpxProviderSecInfo `json:"ipxProviderSecInfoList,omitempty" yaml:"ipxProviderSecInfoList" bson:"ipxProviderSecInfoList" mapstructure:"IpxProviderSecInfoList"`
	// Fully Qualified Domain Name
	Sender string `json:"sender,omitempty" yaml:"sender" bson:"sender" mapstructure:"Sender"`
}
