/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type SecurityCapability string

// List of SecurityCapability
const (
	SecurityCapability_TLS SecurityCapability = "TLS"
	SecurityCapability_PRINS SecurityCapability = "PRINS"
)