/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SecNegotiateReqData struct {
	// Fully Qualified Domain Name
	Sender string `json:"sender" yaml:"sender" bson:"sender" mapstructure:"Sender"`
	SupportedSecCapabilityList []SecurityCapability `json:"supportedSecCapabilityList" yaml:"supportedSecCapabilityList" bson:"supportedSecCapabilityList" mapstructure:"SupportedSecCapabilityList"`
	Var3GppSbiTargetApiRootSupported bool `json:"3GppSbiTargetApiRootSupported,omitempty" yaml:"3GppSbiTargetApiRootSupported" bson:"3GppSbiTargetApiRootSupported" mapstructure:"Var3GppSbiTargetApiRootSupported"`
	PlmnIdList []PlmnId `json:"plmnIdList,omitempty" yaml:"plmnIdList" bson:"plmnIdList" mapstructure:"PlmnIdList"`
}
